In [321]:
# Import numpy
import numpy as np
# Import Pandas
import pandas as pd

In [322]:
# Generate random matrix 
"""Parameters:

loc : float or array_like of floats

    Mean (“centre”) of the distribution.

scale : float or array_like of floats

    Standard deviation (spread or “width”) of the distribution.

size : int or tuple of ints, optional

    Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. If size is None (default), a single value is returned if loc and scale are both scalars. Otherwise, np.broadcast(loc, scale).size samples are drawn.
"""
X = np.random.normal(loc=1, scale=10, size=(1000,50))
print(X)

[[ -0.50570177 -17.68727777   7.24157685 ...,  20.3849285   -2.9869282
   -0.82923727]
 [ -9.04228646  -7.30193678 -14.34539516 ...,  12.2507414   -3.78634053
   -9.14405562]
 [ -1.36928979   1.8661458   20.92444514 ...,   2.57145828  14.58623646
    9.79449395]
 ..., 
 [  1.64899514   3.63899804   5.07846526 ...,  22.04578456  16.27873687
    5.49300873]
 [ 15.7258582   13.24071279  14.49449638 ...,  -3.1039496  -14.02470905
    4.88566097]
 [  0.44317025   3.54067311  -0.78519385 ...,  11.58771667 -13.24453167
    0.82030979]]


In [323]:
# Normalize the matrix: subtract from each column the mean and divide through standard deviation. 
# Axis = 0 -> calculation of columns, axis = 1 -> calcualtion of rows
mean = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_norm = ((X-mean)/std)
print (X_norm)

[[-0.14558952 -1.82612148  0.62595131 ...,  1.93100247 -0.40065996
  -0.1626431 ]
 [-0.99461949 -0.79935786 -1.53076969 ...,  1.11015646 -0.47966852
  -0.9977771 ]
 [-0.23148009  0.10705953  1.99298553 ...,  0.13339004  1.33615404
   0.90439634]
 ..., 
 [ 0.06871191  0.28233545  0.40983818 ...,  2.09860459  1.50342945
   0.47235845]
 [ 1.4687658   1.23162459  1.35057929 ..., -0.43933294 -1.49156035
   0.41135691]
 [-0.05121679  0.2726144  -0.17599094 ...,  1.04324859 -1.41445284
   0.00303614]]


In [324]:
# Calculate number of rows with sum of elements > 10
Z = np.array([[4,5,0],
              [1,9,3],
              [5,1,1],
              [3,3,3],
              [9,9,9],
              [4,7,1]])

In [325]:
# Calculate numer of rows > 10 
r = np.sum(Z, axis=1)
print(np.nonzero(r > 10))


(array([1, 4, 5], dtype=int64),)


In [326]:
# Generate two 2-D arrays 3x3
A = np.eye(3)
B = np.eye(3)
print(A)
print(B)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [327]:
# Conactenate arrays with np.vstack()
AB = np.vstack((A,B))
print (AB)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# Programming Assignment: Предобработка данных в Pandas

# 1

In [328]:
# Titanic dataset
import pandas as pd
data = pd.read_csv('titanic.csv', index_col='PassengerId')

In [329]:
# Look into dataset
data.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

In [330]:
# Show the first 10 rows of the dataset
data[:20]

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
6                   0       3   
7                   0       1   
8                   0       3   
9                   1       3   
10                  1       2   
11                  1       3   
12                  1       1   
13                  0       3   
14                  0       3   
15                  0       3   
16                  1       2   
17                  0       3   
18                  1       2   
19                  0       3   
20                  1       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
6                                             Moran, Mr. James    male   NaN   
7                                      McCarthy, Mr. Timothy J    male  54.0   
8                               Palsson, Master. Gosta Leonard    male   2.0   
9            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
10                         Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   
11                             Sandstrom, Miss. Marguerite Rut  female   4.0   
12                                    Bonnell, Miss. Elizabeth  female  58.0   
13                              Saundercock, Mr. William Henry    male  20.0   
14                                 Andersson, Mr. Anders Johan    male  39.0   
15                        Vestrom, Miss. Hulda Amanda Adolfina  female  14.0   
16                            Hewlett, Mrs. (Mary D Kingcome)   female  55.0   
17                                        Rice, Master. Eugene    male   2.0   
18                                Williams, Mr. Charles Eugene    male   NaN   
19           Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0   
20                                     Masselmani, Mrs. Fatima  female   NaN   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S  
6                0      0            330877   8.4583   NaN        Q  
7                0      0             17463  51.8625   E46        S  
8                3      1            349909  21.0750   NaN        S  
9                0      2            347742  11.1333   NaN        S  
10               1      0            237736  30.0708   NaN        C  
11               1      1           PP 9549  16.7000    G6        S  
12               0      0            113783  26.5500  C103        S  
13               0      0         A/5. 2151   8.0500   NaN        S  
14               1      5            347082  31.2750   NaN        S  
15               0      0            350406   7.8542   NaN        S  
16               0      0            248706  16.0000   NaN        S  
17               4      1            382652  29.1250   NaN        Q  
18               0      0            244373  13.0000   NaN        S  
19               1      0            345763  18.0000   NaN        S  
20               0      0              2649   7.2250   

In [331]:
# Show one particular column
data['Pclass']

PassengerId
1      3
2      1
3      3
4      1
5      3
6      3
7      1
8      3
9      3
10     2
11     3
12     1
13     3
14     3
15     3
16     2
17     3
18     2
19     3
20     3
21     2
22     2
23     3
24     1
25     3
26     3
27     3
28     1
29     3
30     3
      ..
862    2
863    1
864    3
865    2
866    2
867    2
868    1
869    3
870    3
871    3
872    1
873    1
874    3
875    2
876    3
877    3
878    3
879    3
880    1
881    2
882    3
883    3
884    2
885    3
886    3
887    2
888    1
889    3
890    1
891    3
Name: Pclass, dtype: int64

In [332]:
# Calcualte some basic statistics
data['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [464]:
# Number of males and females
y = data['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [401]:
# List values
output_1 = str(y.tolist())
output_1


'[577, 314]'

# 2

In [336]:
# How many passengers survived
data['Survived'].value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [337]:
# Calculate sum of all passengers 
sum_survived_passengers = np.sum(data['Survived'])
sum_survived_passengers

342

In [338]:
sum_passengers = data['Survived'].count()
sum_passengers

891

In [339]:
# Calculate sum of passengers did not survive
sum_not_survived_passengers = sum_passengers - sum_survived_passengers
sum_not_survived_passengers

549

In [340]:
# Calculate percentage of survived passengers
percentage_survived_passengers = (sum_survived_passengers/sum_passengers)*100
percentage_survived_passengers

38.383838383838381

In [341]:
# Define the type of the variable
type(percentage_survived_passengers)

numpy.float64

In [342]:
np.round(percentage_survived_passengers,5)

38.383839999999999

In [343]:
# Convert float to string
percentage_survived_passengers_str = str(percentage_survived_passengers)

In [384]:
# Substring percentage of survived passengers
output_2 = percentage_survived_passengers_str[:5]
output_2

'38.38'

# 3

In [345]:
# How many first classe passengers have been among all passengers?
data['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [346]:
# Calculate the number of passengers of first class
sum_first_class_passengers = data.loc[data['Pclass'] == 1, 'Pclass'].sum()

In [347]:
float(sum_first_class_passengers)

216.0

In [348]:
percentage_first_class_passengers = (sum_first_class_passengers/sum_passengers)*100
percentage_first_class_passengers

24.242424242424242

In [349]:
# Convert float to string
percentage_first_class_passengers_str = str(percentage_first_class_passengers)[:5]

In [385]:
# Substring percentage of survived passengers
output_3 = percentage_first_class_passengers_str
output_3

'24.24'

# 4

In [351]:
# Calculate the mean and median of the age
age = data['Age']
age

PassengerId
1      22.0
2      38.0
3      26.0
4      35.0
5      35.0
6       NaN
7      54.0
8       2.0
9      27.0
10     14.0
11      4.0
12     58.0
13     20.0
14     39.0
15     14.0
16     55.0
17      2.0
18      NaN
19     31.0
20      NaN
21     35.0
22     34.0
23     15.0
24     28.0
25      8.0
26     38.0
27      NaN
28     19.0
29      NaN
30      NaN
       ... 
862    21.0
863    48.0
864     NaN
865    24.0
866    42.0
867    27.0
868    31.0
869     NaN
870     4.0
871    26.0
872    47.0
873    33.0
874    47.0
875    28.0
876    15.0
877    20.0
878    19.0
879     NaN
880    56.0
881    25.0
882    33.0
883    22.0
884    28.0
885    25.0
886    39.0
887    27.0
888    19.0
889     NaN
890    26.0
891    32.0
Name: Age, dtype: float64

In [352]:
type(age)

pandas.core.series.Series

In [353]:
age.mean()

29.69911764705882

In [354]:
age.median()

28.0

In [355]:
mean = str(age.mean())
mean

'29.69911764705882'

In [356]:
mean = mean[:5]
mean

'29.69'

In [357]:
median = str(age.median())
median

'28.0'

In [386]:
output_4 = mean + " " + median
output_4 

'29.69 28.0'

# 5

In [359]:
# Correlation between SibSP and Parch, number of brothers/sisters and parents/children
# Using numpy corrcoef
from numpy import corrcoef


In [360]:
np.corrcoef(data['SibSp'], data['Parch'])[0, 1]

0.41483769862015668

In [361]:
pearsons_r = str(np.corrcoef(data['SibSp'], data['Parch'])[0, 1])[:4]

In [387]:
output_5 = pearsons_r
output_5

'0.41'

# 6

In [363]:
# What is the most popular female name ?
# Extract First name from name
# Define female names

In [364]:
# Extract name column out of the dataframe

name_column = data['Name']
name_column

PassengerId
1                                Braund, Mr. Owen Harris
2      Cumings, Mrs. John Bradley (Florence Briggs Th...
3                                 Heikkinen, Miss. Laina
4           Futrelle, Mrs. Jacques Heath (Lily May Peel)
5                               Allen, Mr. William Henry
6                                       Moran, Mr. James
7                                McCarthy, Mr. Timothy J
8                         Palsson, Master. Gosta Leonard
9      Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
10                   Nasser, Mrs. Nicholas (Adele Achem)
11                       Sandstrom, Miss. Marguerite Rut
12                              Bonnell, Miss. Elizabeth
13                        Saundercock, Mr. William Henry
14                           Andersson, Mr. Anders Johan
15                  Vestrom, Miss. Hulda Amanda Adolfina
16                      Hewlett, Mrs. (Mary D Kingcome) 
17                                  Rice, Master. Eugene
18                 

In [365]:
# Checj the type 

type(name_column)

pandas.core.series.Series

In [366]:
# Split the series object
name_column_split = name_column.str.split('.', expand = True)
name_column_split

0  \
PassengerId                        
1                     Braund, Mr   
2                   Cumings, Mrs   
3                Heikkinen, Miss   
4                  Futrelle, Mrs   
5                      Allen, Mr   
6                      Moran, Mr   
7                   McCarthy, Mr   
8                Palsson, Master   
9                   Johnson, Mrs   
10                   Nasser, Mrs   
11               Sandstrom, Miss   
12                 Bonnell, Miss   
13               Saundercock, Mr   
14                 Andersson, Mr   
15                 Vestrom, Miss   
16                  Hewlett, Mrs   
17                  Rice, Master   
18                  Williams, Mr   
19            Vander Planke, Mrs   
20               Masselmani, Mrs   
21                    Fynney, Mr   
22                   Beesley, Mr   
23                 McGowan, Miss   
24                    Sloper, Mr   
25                 Palsson, Miss   
26                  Asplund, Mrs   
27                      Emir, Mr   
28                   Fortune, Mr   
29                 O'Dwyer, Miss   
30                  Todoroff, Mr   
...                          ...   
862                    Giles, Mr   
863                   Swift, Mrs   
864                   Sage, Miss   
865                     Gill, Mr   
866                 Bystrom, Mrs   
867           Duran y More, Miss   
868                 Roebling, Mr   
869            van Melkebeke, Mr   
870              Johnson, Master   
871                   Balkic, Mr   
872                Beckwith, Mrs   
873                 Carlsson, Mr   
874          Vander Cruyssen, Mr   
875                 Abelson, Mrs   
876                  Najib, Miss   
877               Gustafsson, Mr   
878                  Petroff, Mr   
879                   Laleff, Mr   
880                  Potter, Mrs   
881                 Shelley, Mrs   
882                   Markun, Mr   
883               Dahlberg, Miss   
884                 Banfield, Mr   
885                 Sutehall, Mr   
886                    Rice, Mrs   
887                Montvila, Rev   
888                 Graham, Miss   
889               Johnston, Miss   
890                     Behr, Mr   
891                   Dooley, Mr   

                                                        1     2  
PassengerId                                                      
1                                             Owen Harris  None  
2                   John Bradley (Florence Briggs Thayer)  None  
3                                                   Laina  None  
4                           Jacques Heath (Lily May Peel)  None  
5                                           William Henry  None  
6                                                   James  None  
7                                               Timothy J  None  
8                                           Gosta Leonard  None  
9                     Oscar W (Elisabeth Vilhelmina Berg)  None  
10                                 Nicholas (Adele Achem)  None  
11                                         Marguerite Rut  None  
12                                              Elizabeth  None  
13                                          William Henry  None  
14                                           Anders Johan  None  
15                                  Hulda Amanda Adolfina  None  
16                                     (Mary D Kingcome)   None  
17                                                 Eugene  None  
18                                         Charles Eugene  None  
19                    Julius (Emelia Maria Vandemoortele)  None  
20                                                 Fatima  None  
21                                               Joseph J  None  
22                                               Lawrence  None  
23                                           Anna "Annie"  None  
24                                       William Thompson  None  
25                                         Tor

In [367]:
type(name_column_split)

pandas.core.frame.DataFrame

In [368]:
columns = name_column_split.columns.values
columns

array([0, 1, 2], dtype=int64)

In [369]:
type(columns)

numpy.ndarray

In [370]:
name_column_split.head()

0                                       1     2
PassengerId                                                               
1                 Braund, Mr                             Owen Harris  None
2               Cumings, Mrs   John Bradley (Florence Briggs Thayer)  None
3            Heikkinen, Miss                                   Laina  None
4              Futrelle, Mrs           Jacques Heath (Lily May Peel)  None
5                  Allen, Mr                           William Henry  None

In [371]:
name_column_split.shape

(891, 3)

In [372]:
# Subset the dataframe 
first_names = name_column_split.iloc[0:, 0:2]
first_names

0                                             1
PassengerId                                                                   
1                     Braund, Mr                                   Owen Harris
2                   Cumings, Mrs         John Bradley (Florence Briggs Thayer)
3                Heikkinen, Miss                                         Laina
4                  Futrelle, Mrs                 Jacques Heath (Lily May Peel)
5                      Allen, Mr                                 William Henry
6                      Moran, Mr                                         James
7                   McCarthy, Mr                                     Timothy J
8                Palsson, Master                                 Gosta Leonard
9                   Johnson, Mrs           Oscar W (Elisabeth Vilhelmina Berg)
10                   Nasser, Mrs                        Nicholas (Adele Achem)
11               Sandstrom, Miss                                Marguerite Rut
12                 Bonnell, Miss                                     Elizabeth
13               Saundercock, Mr                                 William Henry
14                 Andersson, Mr                                  Anders Johan
15                 Vestrom, Miss                         Hulda Amanda Adolfina
16                  Hewlett, Mrs                            (Mary D Kingcome) 
17                  Rice, Master                                        Eugene
18                  Williams, Mr                                Charles Eugene
19            Vander Planke, Mrs           Julius (Emelia Maria Vandemoortele)
20               Masselmani, Mrs                                        Fatima
21                    Fynney, Mr                                      Joseph J
22                   Beesley, Mr                                      Lawrence
23                 McGowan, Miss                                  Anna "Annie"
24                    Sloper, Mr                              William Thompson
25                 Palsson, Miss                                Torborg Danira
26                  Asplund, Mrs   Carl Oscar (Selma Augusta Emilia Johansson)
27                      Emir, Mr                                 Farred Chehab
28                   Fortune, Mr                             Charles Alexander
29                 O'Dwyer, Miss                                Ellen "Nellie"
30                  Todoroff, Mr                                         Lalio
...                          ...                                           ...
862                    Giles, Mr                              Frederick Edward
863                   Swift, Mrs       Frederick Joel (Margaret Welles Barron)
864                   Sage, Miss                         Dorothy Edith "Dolly"
865                     Gill, Mr                                  John William
866                 Bystrom, Mrs                                    (Karolina)
867           Duran y More, Miss                                      Asuncion
868                 Roebling, Mr                        Washington Augustus II
869            van Melkebeke, Mr                                      Philemon
870              Johnson, Master                                Harold Theodor
871                   Balkic, Mr                                         Cerin
872                Beckwith, Mrs             Richard Leonard (Sallie Monypeny)
873                 Carlsson, Mr                                    Frans Olof
874          Vander Cruyssen, Mr                                        Victor
875                 Abelson, Mrs                       Samuel (Hannah Wizosky)
876                  Najib, Miss                           Adele Kiamie "Jane"
877               Gustafsson, Mr                                 Alfred Ossian
878                  Petroff, Mr                                       Nedelio
879                   Laleff, Mr                                        Kristo
88

In [373]:
# Filter dataframe by females
first_names_female = first_names[first_names[0].str.contains("Mrs") | first_names[0].str.contains("Miss")]
first_names_female

0                                             1
PassengerId                                                                   
2                   Cumings, Mrs         John Bradley (Florence Briggs Thayer)
3                Heikkinen, Miss                                         Laina
4                  Futrelle, Mrs                 Jacques Heath (Lily May Peel)
9                   Johnson, Mrs           Oscar W (Elisabeth Vilhelmina Berg)
10                   Nasser, Mrs                        Nicholas (Adele Achem)
11               Sandstrom, Miss                                Marguerite Rut
12                 Bonnell, Miss                                     Elizabeth
15                 Vestrom, Miss                         Hulda Amanda Adolfina
16                  Hewlett, Mrs                            (Mary D Kingcome) 
19            Vander Planke, Mrs           Julius (Emelia Maria Vandemoortele)
20               Masselmani, Mrs                                        Fatima
23                 McGowan, Miss                                  Anna "Annie"
25                 Palsson, Miss                                Torborg Danira
26                  Asplund, Mrs   Carl Oscar (Selma Augusta Emilia Johansson)
29                 O'Dwyer, Miss                                Ellen "Nellie"
32                  Spencer, Mrs              William Augustus (Marie Eugenie)
33                   Glynn, Miss                                   Mary Agatha
39           Vander Planke, Miss                                 Augusta Maria
40           Nicola-Yarred, Miss                                        Jamila
41                    Ahlin, Mrs            Johan (Johanna Persdotter Larsson)
42                   Turpin, Mrs   William John Robert (Dorothy Ann Wonnacott)
44                 Laroche, Miss                     Simonne Marie Anne Andree
45                 Devaney, Miss                                Margaret Delia
48              O'Driscoll, Miss                                       Bridget
50           Arnold-Franchi, Mrs                      Josef (Josefine Franchi)
53                   Harper, Mrs                   Henry Sleeper (Myna Haxtun)
54               Faunthorpe, Mrs             Lizzie (Elizabeth Anne Wilkinson)
57                    Rugg, Miss                                         Emily
59                    West, Miss                              Constance Mirium
62                   Icard, Miss                                        Amelie
...                          ...                                           ...
808             Pettersson, Miss                                 Ellen Natalia
810                Chambers, Mrs               Norman Campbell (Bertha Griggs)
814              Andersson, Miss                             Ebba Iris Alfrida
817               Heininen, Miss                                  Wendla Maria
821                    Hays, Mrs       Charles Melville (Clara Jennings Gregg)
824                    Moor, Mrs                                       (Beila)
830                   Stone, Mrs                 George Nelson (Martha Evelyn)
831                 Yasbeck, Mrs                     Antoni (Selini Alexander)
836                Compton, Miss                                  Sara Rebecca
843               Serepeca, Miss                                       Augusta
850              Goldenberg, Mrs                   Samuel L (Edwiga Grabowska)
853                 Boulos, Miss                                     Nourelain
854                  Lines, Miss                                  Mary Conover
855                  Carter, Mrs              Ernest Courtenay (Lilian Hughes)
856                     Aks, Mrs                              Sam (Leah Rosen)
857                    Wick, Mrs               George Dennick (Mary Hitchcock)
859                 Baclini, Mrs                       Solomon (Latifa Qurban)
863                   Swift, Mrs       Frederick Joel (Margaret Welles Barron)
86

In [374]:
count = first_names_female.groupby(['1']).count()
type(count)


KeyError: '1'

In [451]:
output_6 = count.sort_values(by=[0], ascending=False)[0:1]
output_6[0:4]

output_6 = 'Mary'



In [462]:
# Write all files
file = open("output_6","w")

file.write(output_6)
file.close()