In [6]:
#Let's get started...
# Importing the modules Pandas and Numpy
import pandas as pd
import numpy as np


# Let's load the data
url = "D:/Python/Kaggle/Titanic/train.csv"
data = pd.read_csv(url)

test=pd.read_csv("D:/Python/Kaggle/Titanic/test.csv")

In [7]:
# Data is loaded now. Let's see the first few lines
data.head()

test.head()



PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [8]:
# Cool! But do we need all the columns?
# First of all, what we need to predict?
# Here we are gonna predict whether a passenger has survived or not?
# Here Survived will be the target column

columns_target= ['Survived']

# Now for predicting whether a passenger has survived or not, what we need to know about the passenger?
# Age of the passenger? Sex? Does that have any effect?
# Or Pclasse? Or the fare of the ticket? Or all the factors contribute to survival?
# Here let's take all the four columns for our predictive model

columns_train=['Age','Pclass','Sex','Fare']


# Let's take the columns and separate data

X=data[columns_train]
y=data[columns_target]

# The data is separated are we done?
# Not yet, because we need to prepare our data, so that there is no incomaptible data in the dtaa
# Incompatible? Ya like infinite Age..
# Basically checking whether there are aby NaN values in the data, let's check one by one

X['Sex'].isnull().sum()
# Cool, all Sex values are there

X['Sex'].isnull().sum()
# Cool check fare

X['Age'].isnull().sum()
# Woo, there are 177 rows with NaN values
# What to do with them?
# Dropping all of them? Dropping 177 rows can change the data alot so NO
# Then what to do?
# we can fill the NaN with Mean or Median of the existing values..
# Here we go with Median...
X['Age']=X['Age'].fillna(X['Age'].median())
X['Age'].head()
# Cool, we are done with the NaN values
# So what now? Is our data prepared for training?
# Not really... Not for now... What else we need to do?
# In sklearn we cannot pass string values as categorical variable
# So? Here we have Sex that has a categorical value with Values Male and Female
# Here we need to convert it to Integer values, we take Male as o and Female as 1
d={'male':0,'female':1}
X['Sex']=X['Sex'].apply(lambda x:d[x])
X['Sex'].head()



C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:39: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:48: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


0    0
1    1
2    1
3    1
4    0
Name: Sex, dtype: int64

In [9]:
# Now let's see the final dataset
X.head()


Age  Pclass  Sex     Fare
0  22.0       3    0   7.2500
1  38.0       1    1  71.2833
2  26.0       3    1   7.9250
3  35.0       1    1  53.1000
4  35.0       3    0   8.0500

In [10]:
# Cool, now what?
# Let's split teh data to train a test dataset

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.33, random_state=42)

# Yeah, we splitted the data successfully

# Support Vector Machine


In [11]:
# Now let's train our model with the train part of the split
# Here we have to select a model
# Here we will use a Linear Support Vector Machine or a Support Vector Machine which separates the data with line or
# linearily separate the data...

from sklearn import svm
clf=svm.LinearSVC()

# Now let's train our model

clf.fit(X_train, y_train.values.ravel())

# Cool, let's go ahead


LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [7]:
# Cool, we just trained our first model
# Now let's make some prediction

print(clf.predict(X_test[0:1]))

# Cool, let's predict for multiple values

print(clf.predict(X_test[0:10]))



[0]
[0 0 0 1 1 1 0 0 1 1]


In [8]:
# Cool!
# Now what? Let's check the accuracy of this model
# It's easy, let's do it
print(clf.score(X_test,y_test))

0.806779661017


In [22]:
feature_cols = ['PassengerId']

# Creating new data frame for final submission
X_new = test.loc[:, columns_train]


In [23]:

# Replacing null vlaues with median
X_new['Age']=X_new['Age'].fillna(X_new['Age'].median())
X_new['Fare']=X_new['Fare'].fillna(X_new['Fare'].median())


# Recoding sex to integers
d={'male':0,'female':1}
X_new['Sex']=X_new['Sex'].apply(lambda x:d[x])



In [34]:

# Showing shape of data frame
X_new

# Check for null values

#X_new['Fare'].isnull().sum()
# Cool, all Sex values are there


#X_new.value_counts(dropna = False)[np.nan]

# Predicting target variable for test
new_pred_class_svm = clf.predict(X_new)

# Printing array
new_pred_class_svm

array([0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0,

In [71]:
pd.DataFrame({'PassengerId':test.PassengerId, 'Survived': new_pred_class_svm}).set_index('PassengerId').to_csv('submission_svm.csv')

# Random Forest 

In [72]:
# Import random forest classifier

from sklearn.ensemble import RandomForestClassifier

# Importing log_loss

from sklearn.metrics import log_loss

# Importing cross validation score

from sklearn.model_selection import cross_val_score


In [73]:

clf = RandomForestClassifier(n_jobs=2,n_estimators=1000)


In [74]:
# Trainig the model

clf.fit(X_train, y_train.values.ravel())

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=1000, n_jobs=2, oob_score=False,
            random_state=None, verbose=0, warm_start=False)

In [75]:
# Build prediction
predictions = clf.predict(X_train)


In [76]:
# Printing log_loss

print('log loss:', log_loss(y_train, predictions))


log loss: 0.753366597191


In [77]:
print("clf score is %2.10f" % clf.score(X_test,y_test))

clf score is 0.8033898305


In [78]:
# Create new column for Random Forest
new_pred_class_rf = clf.predict(X_new)

In [79]:
# Printing the outcome
new_pred_class_rf

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0,

In [80]:
# Create dataset for Random Forest
pd.DataFrame({'PassengerId':test.PassengerId, 'Survived': new_pred_class_rf}).set_index('PassengerId').to_csv('submission_rf.csv')

# K-Nearest Neighbors

In [81]:
# Importing KNeighborsCLassifier

from sklearn.neighbors import KNeighborsClassifier

In [82]:
# Define K-Nearest Neigbors
knn = KNeighborsClassifier()

In [83]:
# Import accuracy score

from sklearn.metrics import accuracy_score


In [84]:
# Import confusion matrix
from sklearn.metrics import confusion_matrix

In [85]:
# Import classification report

from sklearn.metrics import classification_report

In [86]:
# Define K-Nearest Neigbors
knn = KNeighborsClassifier()

In [87]:
# Training the model
knn.fit(X_train,y_train)


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  from ipykernel import kernelapp as app


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [88]:
# Make predictions
predictions = knn.predict(X_test)


In [89]:
print("Accuracy score is %2.10f" % accuracy_score(y_test, predictions))


Accuracy score is 0.7084745763


In [90]:
# Creating confusion matrix
print(confusion_matrix(y_test, predictions))


[[142  33]
 [ 53  67]]


In [91]:
# Print classification report
print(classification_report(y_test, predictions))


             precision    recall  f1-score   support

          0       0.73      0.81      0.77       175
          1       0.67      0.56      0.61       120

avg / total       0.70      0.71      0.70       295



In [92]:
# Create new column for K-Nearest Neighbors
new_pred_class_knn = clf.predict(X_new)

In [93]:
new_pred_class_knn

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0,

In [94]:
# Create dataset for K-Nearest Neighbors
pd.DataFrame({'PassengerId':test.PassengerId, 'Survived': new_pred_class_knn}).set_index('PassengerId').to_csv('submission_knn.csv')

# XGBoost

In [95]:
import os

mingw_path = 'C:\Program Files\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev0\mingw64\bin'

os.environ['PATH'] = mingw_path + ';' + os.environ['PATH']

In [96]:
# Importing XGBoost
import xgboost as xgb

In [97]:
param = {'objective':'binary:logistic', 'n_estimators':2000, 'colsample_bytree':0.7, 'subsample':0.7, 'max_depth':4, 
         'learning_rate':0.3, 'min_child_weight': 5}

In [98]:
# Building XGBoost model
clf = xgb.XGBClassifier(**param)

clf.fit(X_train, y_train, eval_metric='logloss', verbose=True)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:112: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:147: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=0.7, gamma=0, learning_rate=0.3, max_delta_step=0,
       max_depth=4, min_child_weight=5, missing=None, n_estimators=2000,
       n_jobs=1, nthread=None, objective='binary:logistic', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=0.7)

In [99]:
predictions_xgb = clf.predict(X_test)

In [100]:
# printing log loss
print('log loss:', log_loss(y_test, preds))

log loss: 6.67366455608


In [101]:
# Create new column for XGBoost
new_pred_class_xgb = clf.predict(X_new)

In [102]:
# Print the array
new_pred_class_xgb

array([0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0,

In [103]:
# Create dataset for XGBoost
pd.DataFrame({'PassengerId':test.PassengerId, 'Survived': new_pred_class_xgb}).set_index('PassengerId').to_csv('submission_xgb.csv')